"""Executable deterministic capabilities, not a count of running LLMs."""
import copy

FORMULAS = [
    {'id':'execution_fee','label':'执行 Gas 费','formula':'gasUsed × effectiveGasPrice ÷ 10¹⁸ = ETH','limitation':'使用回执实际 gasUsed；不是 gasLimit × maxFeePerGas。'},
    {'id':'blob_fee','label':'Blob 数据费','formula':'blobGasUsed × blobGasPrice ÷ 10¹⁸ = ETH（仅有此费用时）','limitation':'普通交易为 0；type=3 必须有对应回执字段。'},
    {'id':'actual_fee','label':'交易实际费用','formula':'执行 Gas 费 + Blob 数据费','limitation':'Ethereum 主网交易费用；不含链下服务费，也不推断代付关系。'},
    {'id':'value','label':'尝试值与成功外层转移值','formula':'尝试值 = transaction.value；成功外层值 = status=1 ? value : 0','limitation':'成功外层值不是账户净流出：合约内部转账、退款、代币转移未计入。'},
    {'id':'gas_ratio','label':'Gas 使用比例','formula':'gasUsed ÷ gasLimit × 100%，四舍五入至 2 位小数','limitation':'仅 gasLimit > 0 且 0 ≤ gasUsed ≤ gasLimit 时计算；比例高不证明 gas 不足。'},
]
_SKILLS = [
 ('COL-01','网络身份核对','collect','核对 Ethereum chainId = 1。'),
 ('COL-02','Finalized 检查点读取','collect','读取 finalized 高度与时间，不把 pending 当已确认。'),
 ('COL-03','指定交易定位','collect','严格校验 32 字节交易哈希，只查询固定 RPC。'),
 ('COL-04','交易与回执采集','collect','获取最多 6 笔交易及相应回执。'),
 ('VAL-01','区块关联验收','validate','核对交易、回执、规范区块、交易索引和摘要。'),
 ('VAL-02','时间与完整性验收','validate','检查点时效与交易发生时间分开；历史交易可验收。'),
 ('QNT-01','实际费用量化','quantify','整数精确计算执行 Gas 和 Blob 费用。'),
 ('QNT-02','尝试与成功值区分','quantify','失败交易的成功外层转移值为零，费用仍单独计入。'),
 ('QNT-03','Gas 使用比例','quantify','有效分母与合理范围下计算。'),
 ('QNT-04','失败与大额线索','quantify','失败回执和 100 ETH 建议阈值，不作恶意结论。'),
 ('QNT-05','授权调用形状辨识','quantify','识别 approve 最大额度 ABI 形状，不认定授权已生效。'),
 ('EXP-01','证据与备选解释','explain','为规则线索列出事实、替代解释与后续核查。'),
 ('EXP-02','有限时间线整理','explain','保留交易、检查点和采集时间，不虚构跨块资金轨迹。'),
 ('RPT-01','证据回执导出','report','绑定输入、快照、输出与确定性执行阶段。'),
 ('RPT-02','离线全量规则重放','report','重算全部派生输出，拒绝仅重新计算哈希的输出篡改。'),
]
_AGENTS = [('AG-01','链上采集员','collect'),('AG-02','证据验收员','validate'),('AG-03','交易量化员','quantify'),('AG-04','线索解释员','explain'),('AG-05','回执复核员','report')]
HARNESS = [
 {'id':'H-01','name':'只读固定数据源','rule':'仅允许固定 PublicNode 和只读 JSON-RPC 方法；禁止钱包、任意 URL 与链上写入。'},
 {'id':'H-02','name':'网络与关联门槛','rule':'chainId、区块哈希、高度、交易索引、回执及 finalized 关系必须一致。'},
 {'id':'H-03','name':'时间分层','rule':'采集与 finalized 检查点必须相近；历史已确认交易按自己的发生时间展示。'},
 {'id':'H-04','name':'整数与语义边界','rule':'金额整数运算；失败 value 不标记为成功转移；不虚构资产归属或因果。'},
 {'id':'H-05','name':'证据绑定和重放','rule':'验证规范 JSON 哈希与全部确定性输出；不将哈希一致称作来源认证。'},
 {'id':'H-06','name':'有界请求与同源','rule':'最多 6 笔、请求与快照大小受限、RPC 串行采集、部署 POST 需同源。'},
]
LIMITATIONS = [
 '当前实现是 5 个岗位的确定性 Python 工具编排，未接入语言模型研判。',
 '默认只抽样一个 finalized 区块前 6 笔；指定哈希只调查该笔，不是全链扫描或完整资金追踪。',
 '只使用一个公共 RPC；结构关联校验不等于独立共识验证或跨源认证。',
 '线索和备选解释不是欺诈、攻击、合规或投资结论；需要更多证据与人工复核。',
 '回执未签名、未上链；离线重放证明快照与规则输出一致，不能证明快照本身真实。',
 '仅保留量化使用的字段；不包含完整日志、内部调用、代币余额或账户净资产变化。',
]

SKILL_DETAILS = {'COL-01': {'task': '核对 Ethereum chainId = 1。',
            'inputs': 'RPC chainId',
            'outputs': '网络身份记录',
            'metric': 'chainId严格等于1；错链或布尔值拒绝',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': 'test_wrong_chain_rejected / test_boolean_chain_rejected'},
 'COL-02': {'task': '读取 finalized 高度与时间，不把 pending 当已确认。',
            'inputs': '当前finalized区块',
            'outputs': '检查点高度与时间',
            'metric': '检查点年龄−30至1800秒；pending不作已确认',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': 'test_unfinalized_rejected / test_stale_checkpoint_rejected'},
 'COL-03': {'task': '严格校验 32 字节交易哈希，只查询固定 RPC。',
            'inputs': '32字节交易哈希',
            'outputs': '定位后的单笔交易',
            'metric': '只接受0x+64位十六进制；必须匹配请求哈希',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': 'test_invalid_user_inputs / '
                        'test_mocked_specific_hash_and_canonical_membership'},
 'COL-04': {'task': '获取最多 6 笔交易及相应回执。',
            'inputs': '区块交易及对应回执',
            'outputs': '最多6笔归一化样本',
            'metric': '默认样本数=min(6,区块交易数)；缺回执拒绝',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': 'test_missing_receipt_rejected / test_mocked_latest_rpc_path_and_cache'},
 'VAL-01': {'task': '核对交易、回执、规范区块、交易索引和摘要。',
            'inputs': '交易、回执与规范区块',
            'outputs': '关联核验结果',
            'metric': 'hash、高度、交易索引及成员关联全部一致；重复数0',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': 'test_receipt_transaction_mismatch_rejected / '
                        'test_wrong_canonical_member_rejected'},
 'VAL-02': {'task': '检查点时效与交易发生时间分开；历史交易可验收。',
            'inputs': '交易时间、采集时间、finalized时间',
            'outputs': '时间分层与完整性检查',
            'metric': '历史交易≤finalized高度；当前检查点不超过1800秒',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': 'test_historical_finalized_transaction_accepted / '
                        'test_stale_checkpoint_rejected'},
 'QNT-01': {'task': '整数精确计算执行 Gas 和 Blob 费用。',
            'inputs': 'gasUsed、effectiveGasPrice、Blob回执字段',
            'outputs': '实际执行费、Blob费及合计',
            'metric': '整数wei精确相乘相加；type=3缺Blob费用字段拒绝',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': 'test_precise_integer_and_ratio_math / test_blob_fee_included / '
                        'test_missing_blob_price_rejected'},
 'QNT-02': {'task': '失败交易的成功外层转移值为零，费用仍单独计入。',
            'inputs': 'transaction.value、receipt.status',
            'outputs': '尝试值与成功外层值',
            'metric': 'status=0时成功外层值=0；费用仍保留',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': 'test_demo_exact_values_and_replay'},
 'QNT-03': {'task': '有效分母与合理范围下计算。',
            'inputs': 'gasUsed、gasLimit',
            'outputs': 'Gas使用比例与观察线索',
            'metric': 'gasLimit>0且0≤gasUsed≤gasLimit；比例保留2位小数；≥95%仅作线索',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': 'test_zero_denominator_rejected / test_overused_gas_rejected / '
                        'test_precise_integer_and_ratio_math'},
 'QNT-04': {'task': '失败回执和 100 ETH 建议阈值，不作恶意结论。',
            'inputs': '交易状态、外层value',
            'outputs': '失败与大额尝试值线索',
            'metric': 'status=0或value≥100×10¹⁸wei；阈值为项目观察口径',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': 'test_demo_exact_values_and_replay'},
 'QNT-05': {'task': '识别 approve 最大额度 ABI 形状，不认定授权已生效。',
            'inputs': '目标地址与调用数据',
            'outputs': 'approve最大额度形状线索',
            'metric': '选择器095ea7b3+64字节ABI参数；正确地址填充；额度=2²⁵⁶−1',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': '授权形状、合约创建与格式边界测试；规则见server/chain.py'},
 'EXP-01': {'task': '为规则线索列出事实、替代解释与后续核查。',
            'inputs': '规则线索及证据字段',
            'outputs': '事实、备选解释、待补核查',
            'metric': '解释关联交易与命中规则；无证据真实主体或攻击归因0项',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': 'test_recomputed_hash_cannot_hide_derived_tampering'},
 'EXP-02': {'task': '保留交易、检查点和采集时间，不虚构跨块资金轨迹。',
            'inputs': '交易区块、finalized检查点、采集时点',
            'outputs': '有限调查时间线',
            'metric': '三种时间独立呈现；不虚构同块秒级先后或跨块资金路径',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': 'test_historical_finalized_transaction_accepted / '
                        'test_recomputed_hash_cannot_hide_derived_tampering'},
 'RPT-01': {'task': '绑定输入、快照、输出与确定性执行阶段。',
            'inputs': '输入、冻结快照、计算输出与执行阶段',
            'outputs': '可下载JSON回执',
            'metric': '文件≤500KiB；5个阶段均绑定输入输出摘要',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': 'test_demo_exact_values_and_replay / test_size_bound'},
 'RPT-02': {'task': '重算全部派生输出，拒绝仅重新计算哈希的输出篡改。',
            'inputs': '完整下载回执',
            'outputs': '摘要与全量规则重放结果',
            'metric': '原包重放通过；改派生输出后即使重算哈希仍拒绝',
            'schedule': '用户提交调查或导入回执时触发；无定时巡链',
            'recipient': '链上调查者与人工复核者',
            'delivery': '页面展示与JSON下载',
            'validation': '确定性工具已实现并测试；示例与真实读取分开',
            'evidence': 'test_recomputed_hash_cannot_hide_derived_tampering / '
                        'test_old_receipt_replay_uses_collection_time'}}

def catalog():
    skills=[{'id':i,'name':n,'stage':s,'status':'implemented_deterministic','description':d,**SKILL_DETAILS.get(i,{})} for i,n,s,d in _SKILLS]
    return {'project':'江城链察','version':'1.0.0','skills':skills,
            'agents':[{'id':i,'name':n,'stage':s,'executor':'deterministic_python_tool','skills':[x['id'] for x in skills if x['stage']==s]} for i,n,s in _AGENTS],
            'harness':copy.deepcopy(HARNESS),'formulas':copy.deepcopy(FORMULAS),'limitations':LIMITATIONS.copy()}
