import { useEffect, useState } from 'react';
import { api, useAction, Shell, Hero, Glass, Heading, ErrorBox, Tag, Checks, Evidence, CatalogView, stamp, short, display, ArrowUpRight } from './ui';
import type { Catalog, CheckItem, Item } from './ui';
type Transaction={hash:string;from:string;to:string|null;status:number;value_eth:string;settled_outer_value_eth:string;gas_used:string;gas_limit:string;gas_use_ratio_percent:string;actual_fee_eth:string;execution_fee_wei:string;blob_fee_wei:string;explorer_url:string|null};
type Finding={id:string;rule_id:string;transaction_hash:string;label:string;severity:string;observation:string;evidence_fields:unknown;limitation:string};
type Hypothesis={id:string;transaction_hash:string;title:string;facts:string[];possible_explanations:string[];next_checks:string[];conclusion_status:string};
type Receipt={mode:string;issued_at:string;receipt_hash:string;output:{source:{name:string;block_number:number;block_hash:string;transaction_time:string;collected_at:string;finalized_block_number:number;collection_duration_ms:number;historical_transaction:boolean;explorer_url:string|null};summary:{sample_count:number;success_count:number;failed_count:number;finding_count:number;attempted_value_eth:string;settled_outer_value_eth:string;actual_fee_eth:string};sampled_transactions:Transaction[];findings:Finding[];hypotheses:Hypothesis[];timeline:{id:string;time:string;kind:string;title:string;detail:string}[]};checks:CheckItem[];execution_trace:Item[];limitations:string[]};
export default function App(){
 const [catalog,setCatalog]=useState<Catalog>();const [catalogError,setCatalogError]=useState('');const [hash,setHash]=useState('');const [inputError,setInputError]=useState('');const action=useAction<Receipt>();
 useEffect(()=>{const controller=new AbortController();api<Catalog>('catalog',undefined,controller.signal).then(setCatalog).catch(e=>{if(!controller.signal.aborted)setCatalogError(String(e.message));});return()=>controller.abort();},[]);
 async function investigate(mode:'live'|'demo',latest=false){setInputError('');const transaction=hash.trim();if(mode==='live'&&!latest&&transaction&&!/^0x[0-9a-fA-F]{64}$/.test(transaction)){setInputError('请输入完整交易哈希：0x 开头，后接 64 位十六进制字符。');return;}await action.run('investigate',mode==='live'&&!latest&&transaction?{mode,transaction_hash:transaction}:{mode});}
 return <Shell kind="chain" busy={action.busy}><Hero number="02" title="链上发生了什么？" em="从一笔交易，追问到证据。" description="为协议运营、研究与风控提供可复查的调查起点：核对执行结果，精确计算成本，拆开已知事实、可能解释和下一步核查。" steps={['读取交易','核对回执','定位线索','重放证据']}/>
 <Glass className="work-card" id="workbench"><Heading kicker="INVESTIGATE / 调查工作台" title="从真实问题开始。"><Tag>Ethereum 主网 · 只读</Tag></Heading><form className="form-grid" onSubmit={e=>{e.preventDefault();void investigate('live');}}><label>交易哈希 <span className="muted">留空则采样当前 finalized 区块的前 6 笔交易</span><input value={hash} onChange={e=>setHash(e.target.value)} placeholder="0x…" spellCheck={false} autoComplete="off" disabled={action.busy} aria-describedby="hash-help"/></label><button type="submit" className="primary" disabled={action.busy}>{action.busy?'正在收集证据…':hash.trim()?'调查这笔交易':'调查最新区块'}<ArrowUpRight size={17}/></button></form><p className="fine" id="hash-help">只接收已 finalized 的主网交易。单一公共 RPC 来源；不读取私钥、不发送链上交易。调查结果保留在当前页面，可下载留存。</p><div className="actions"><button className="secondary" disabled={action.busy} onClick={()=>void investigate('live',true)}>采样最新区块</button><button className="secondary" disabled={action.busy} onClick={()=>void investigate('demo')}>运行合成案例</button><span className="muted">合成案例包含失败转账、高 Gas 使用等边界情形</span></div><ErrorBox error={inputError||action.error}/>{action.busy&&<p role="status" className="pending">依次读取交易、回执和 finalized 检查点，随后重算费用与线索。请稍候。</p>}{action.data&&<Report receipt={action.data}/>}</Glass>
 <Evidence receipt={action.data} name="江城链察-调查证据"/>
 <section className="method-section" id="method"><Heading kicker="METHOD / 调查方法" title="每一步，都能追问依据。"/><div className="info-columns"><div><h3>解决三个具体问题</h3><p>交易到底成功了吗？实际花了多少手续费？金额或 Gas 表现值得从哪里继续核查？</p><p>工具从交易与回执计算事实，再给出多种解释和补证方向。线索不等于攻击判断，交易外层金额也不等于完整资金流。</p></div><div><h3>五个岗位，一份证据</h3><p>采集、核验、计算、研判、复核按顺序交接。当前由确定性 Python 工具执行，保留阶段摘要和技能编号。</p><p>覆盖有界样本的交易质量与资金行为。尚未接入地址身份、内部调用、代币日志全量追踪或跨来源共识核验。</p></div></div><div className="formula-grid">{catalog?.formulas?.map(f=><div key={display(f.id)}><h3>{display(f.label)}</h3><code>{display(f.formula)}</code><p>{display(f.limitation)}</p></div>)}</div></section>
 <CatalogView catalog={catalog} error={catalogError}/></Shell>;
}
function Report({receipt:r}:{receipt:Receipt}){const o=r.output;const s=o.summary;return <section className="result-card investigation" aria-live="polite"><div className="result-head"><div><Tag>{r.mode==='live'?'实际链上读取':'合成案例 · 非真实交易'}</Tag><h3>{s.finding_count?`发现 ${s.finding_count} 条待核查线索。`:'样本内未触发当前线索规则。'}</h3><p>{stamp(r.issued_at)}</p></div><Tag>区块 {o.source.block_number}</Tag></div><p className="muted">{r.mode==='live'?`${o.source.name} · ${s.sample_count} 笔有界样本`:'固定示例数据，供复现规则使用'} · 线索只说明规则被触发，不代表恶意或攻击。</p>
 <div className="metrics"><div className="metric"><span>样本执行</span><strong>{s.success_count} <small>成功 / {s.failed_count} 失败</small></strong></div><div className="metric"><span>成功交易的外层转移</span><strong className="exact">{s.settled_outer_value_eth}<small> ETH</small></strong><small>尝试发送 {s.attempted_value_eth} ETH · 不等于净资金流</small></div><div className="metric"><span>实际费用合计</span><strong className="exact">{s.actual_fee_eth}<small> ETH</small></strong><small>执行 Gas 费用 + Blob 费用（如有）</small></div></div>
 <details className="source-details"><summary>数据时点与来源范围</summary><dl className="catalog-fields"><div><dt>交易所在区块时间</dt><dd>{stamp(o.source.transaction_time)}</dd></div><div><dt>本次采集时间</dt><dd>{stamp(o.source.collected_at)}</dd></div><div><dt>当前 finalized 检查点</dt><dd>{o.source.finalized_block_number}</dd></div><div><dt>历史交易调查</dt><dd>{o.source.historical_transaction?'是，按当前检查点核验已终结状态':'否'}</dd></div><div><dt>采集耗时</dt><dd>{o.source.collection_duration_ms} ms</dd></div><div><dt>区块摘要</dt><dd className="mono">{o.source.block_hash}</dd></div></dl>{o.source.explorer_url&&<a className="text-link" href={o.source.explorer_url} target="_blank" rel="noreferrer">区块浏览器对照 <ArrowUpRight size={14}/></a>}</details>
 <div className="report-section"><h3>交易与成本</h3><div className="table-wrap"><table><thead><tr><th>交易 / 执行</th><th>尝试金额（ETH）</th><th>实际费用（ETH）</th><th>Gas 使用率</th><th>对照</th></tr></thead><tbody>{o.sampled_transactions.map(tx=><tr key={tx.hash}><td><span className="mono">{short(tx.hash)}</span><br/><Tag pass={tx.status===1}>{tx.status===1?'执行成功':'执行失败'}</Tag></td><td className="numeric">{tx.value_eth}</td><td className="numeric">{tx.actual_fee_eth}</td><td>{tx.gas_use_ratio_percent}%</td><td>{tx.explorer_url?<a href={tx.explorer_url} target="_blank" rel="noreferrer" aria-label={`查看交易 ${tx.hash}`}>原始交易 ↗</a>:<span className="muted">合成数据</span>}</td></tr>)}</tbody></table></div><p className="fine">失败交易的尝试金额未计入成功外层转移，但已消耗的 Gas 仍计入费用。金额按整数 Wei 运算后精确展示。</p></div>
 {o.findings.length>0&&<div className="report-section"><h3>触发了哪些规则</h3><div className="findings">{o.findings.map(f=><details key={f.id} className="finding"><summary><span><b>{f.label}</b><small>{short(f.transaction_hash)}</small></span><Tag>{f.severity==='high'?'优先核查':f.severity==='medium'?'需要复核':'观察线索'}</Tag></summary><p>{f.observation}</p><p className="muted">{f.limitation}</p><small>规则 {f.rule_id} · 依据 {display(f.evidence_fields)}</small></details>)}</div></div>}
 {o.hypotheses.length>0&&<div className="report-section"><h3>把事实和解释分开</h3>{o.hypotheses.map(h=><article className="hypothesis" key={h.id}><header><h4>{h.title}</h4><Tag>待补证</Tag></header><div className="hypothesis-columns"><div><span>已知事实</span><ul>{h.facts.map((t,i)=><li key={i}>{t}</li>)}</ul></div><div><span>可能解释</span><ul>{h.possible_explanations.map((t,i)=><li key={i}>{t}</li>)}</ul></div><div><span>下一步核查</span><ul>{h.next_checks.map((t,i)=><li key={i}>{t}</li>)}</ul></div></div></article>)}</div>}
 <details className="report-section"><summary>查看逐项数据检查与岗位交接</summary><Checks items={r.checks}/><ol className="timeline">{r.execution_trace.map((stage,i)=><li key={i}><b>{display(stage.agent_id)}</b><span>{display(stage.stage_id)} · {display(stage.used_skill_ids)}</span><small>输入 {short(display(stage.input_hash))} → 输出 {short(display(stage.output_hash))}</small></li>)}</ol></details><p className="provenance">证据摘要 <code>{r.receipt_hash}</code></p></section>;}
